version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum docker-compose.yml }}
          paths: ~/caches/images.tar
      - run:
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run: pip install docker-compose
      - run: docker-compose pull
      - run: docker-compose build
      - run: docker images
      - run:
          command: |
            mkdir -p ~/caches
            docker save $(docker images -q) -o ~/caches/images.tar
      - save_cache:
          key: docker-{{ checksum docker-compose.yml }}
          paths: ~/caches/images.tar
  test:
    machine: true
    steps:
      - checkout
      - run: pip install docker-compose
      - restore_cache:
          key: docker-{{ checksum docker-compose.yml }}
          paths: ~/caches/images.tar
      - run:
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run: docker-compose pull
      - run: docker-compose build
      - run: docker images
workflows:
  version: 2
  build:
    jobs:
      - generate_cache
      - test:
          requires:
            - generate_cache