version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      # - restore_cache:
      #     key: docker-{{ .Branch }}
      #     paths: ~/caches/node.tar
      # - run:
      #     command: |
      #       docker load -i ~/caches/node.tar | true
      - run:
          name: pull(一回目)
          command: time docker pull node:8.2.1-onbuild
      - run:
          name: pull(二回目)
          command: time docker pull node:8.2.1-onbuild
      - run:
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/node.tar node
      - save_cache:
          key: docker-{{ .Branch }}
          paths: ~/caches/node.tar

  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ .Branch }}
          paths: ~/caches/node.tar
      - run: docker images
      - run: ls ~/caches
      - run:
          command: |
            set +o pipefail
            docker load -i ~/caches/node.tar | true
      - run:
          name: pull(一回目)(キャッシュ)
          command: time docker pull node:8.2.1-onbuild

workflows:
  version: 2
  build:
    jobs:
      - generate_cache
      - test:
          requires:
            - generate_cache