version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: pull(一回目)
          command: time docker pull node:8.2.1-onbuild
      - run:
          name: pull(二回目)
          command: time docker pull node:8.2.1-onbuild
