version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar
      - run:
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run:
          name: pull(一回目)
          command: time docker pull node:8.2.1-onbuild
      - run:
          command: |
            mkdir -p ~/caches
            docker save $(docker images -q) -o ~/caches/images.tar
      - save_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar

  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar
      - run: docker images
      - run: ls ~/caches
      - run:
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run: docker images
      - run:
          name: pull(一回目)(キャッシュ)
          command: docker pull node:8.2.1-onbuild

workflows:
  version: 2
  build:
    jobs:
      - generate_cache
      - test:
          requires:
            - generate_cache